function visualization5GSim_xgboost()
% VISUALIZATION5GSIM_XGBOOST Loads the results from the XGBoost simulation
% and generates six plots showing allocation performance metrics.

clear;
% Load simulation results (generated by res_allocation_xgboost.m)
try
    load('sim_results_xgboost.mat');
catch
    error('SIMULATION RESULTS ERROR: sim_results_xgboost.mat not found. Please run res_allocation_xgboost.m first.');
end

% Data structure: simulationResults(SlotIdx, UEIdx, [1:7])
% Indices: 1=SlotIdx, 2=UEIdx, 3=Latency, 4=PacketSuccess, 5=AppTypeIndex, 6=Predicted_BW, 7=PacketLoss

% --- 1. Bandwidth Allocation Heatmap (Slot vs UE) ---
bwMatrix = squeeze(simulationResults(:, :, 6)); % Predicted_BW
figure;
imagesc(bwMatrix');
colorbar;
xlabel('Time Slot'); 
ylabel('UE Index');
title('1. Predicted Bandwidth Allocation (Mbps) Heatmap');
set(gca, 'YDir', 'normal'); % Flip Y axis for natural viewing
colormap(parula);


% --- 2. Average Bandwidth per Application Type ---
% Create groups for boxplot/bar plot using the AppTypeIndex
allPredictedBW = simulationResults(:, :, 6);
allAppIndices = simulationResults(:, :, 5);

% Calculate average BW per application
avgBWPerApp = zeros(1, numAppTypes);
for i = 1:numAppTypes
    indices = allAppIndices == i;
    avgBWPerApp(i) = mean(allPredictedBW(indices));
end

figure;
bar(avgBWPerApp);
set(gca, 'XTickLabel', app_types, 'XTickLabelRotation', 45);
title('2. Average Allocated Bandwidth per Application Type');
ylabel('Average Bandwidth (Mbps)');
grid on;


% --- 3. Latency Distribution per Application Type (Boxplot) ---
latencyData = cell(1, numAppTypes);
for i = 1:numAppTypes
    indices = allAppIndices == i;
    latencyMatrix = simulationResults(:, :, 3); % Latency
    latencyData{i} = latencyMatrix(indices);
end

% Combine data and create grouping vector for boxplot
combinedLatency = [];
groupLabels = [];
for i = 1:numAppTypes
    data = latencyData{i};
    combinedLatency = [combinedLatency; data];
    groupLabels = [groupLabels; i * ones(size(data))];
end

figure;
boxplot(combinedLatency, groupLabels, 'Labels', app_types);
title('3. Latency Distribution per Application Type');
ylabel('Simulated Latency (ms)');
set(gca, 'XTickLabelRotation', 45);
grid on;


% --- 4. System-Wide Average Bandwidth Over Time ---
avgBWPerSlot = mean(bwMatrix, 2); % Average BW across all UEs for each slot

figure;
plot(1:numSlots, avgBWPerSlot, '-b', 'LineWidth', 1.5);
xlabel('Time Slot Index');
ylabel('Average Allocated Bandwidth (Mbps)');
title('4. System-Wide Average Bandwidth Over Time');
grid on;


% --- 5. Packet Loss Rate (PLR) Heatmap ---
plrMatrix = squeeze(simulationResults(:, :, 7)); % Packet Loss
figure;
imagesc(plrMatrix');
colorbar;
xlabel('Time Slot');
ylabel('UE Index');
title('5. Simulated Packet Loss Rate (PLR) Heatmap');
set(gca, 'YDir', 'normal');
colormap(flipud(gray)); % Black/White scale for visual contrast

% --- 6. Bandwidth vs. Latency Scatter Plot ---
allLatencies = simulationResults(:, :, 3); % Latency
allBW = simulationResults(:, :, 6); % Predicted_BW

figure;
scatter(allBW(:), allLatencies(:), 10, allAppIndices(:), 'filled');
colorbar('Ticks', 1:numAppTypes, 'TickLabels', app_types);
xlabel('Predicted Allocated Bandwidth (Mbps)');
ylabel('Simulated Latency (ms)');
title('6. Bandwidth Allocation vs. Latency');
grid on;

end