%% 
clear;
% Load the simulation results generated by the DNN agent
% NOTE: The file is now saved in the current directory, so we load it directly.
load('sim_results_dnn.mat'); 

% Define Slice and Resource Names
sliceNames = {'eMBB', 'URLLC', 'mMTC'};
resourceNames = {'Bandwidth (MHz)', 'Power (dBm)', 'PRBs', 'MCS', 'Antennas', 'Queue Size', 'Latency Budget (ms)'};

% Define the resource templates again to calculate GBR per slice
% [Bandwidth (MHz), Power (dBm), PRBs, MCS, Antennas, Queue, LatencyBudget (ms)]
resourcesPerSlice = [
    100, 23, 40, 8, 2, 5, 100;    % 1: eMBB (MCS 8 -> 16QAM, bps=4)
    10, 18, 10, 2, 1, 1, 1;       % 2: URLLC (MCS 2 -> QPSK, bps=2)
    5, 15, 2, 1, 1, 2, 1000       % 3: mMTC (MCS 1 -> QPSK, bps=2)
];

% Pre-calculate the GBR for each slice based on the fixed formula: BW * 0.1 * bps
% NOTE: Assuming the GBR multiplier was 0.1 in the simulation script (as fixed previously)
gbrValues = zeros(1, 3);
for s = 1:3
    BW = resourcesPerSlice(s, 1);
    MCS = resourcesPerSlice(s, 4);
    if MCS <= 4, bps = 2; elseif MCS <= 16, bps = 4; else bps = 6; end
    gbrValues(s) = BW * 0.1 * bps;
end

%% --- 1. Display Per-Slot Metrics (For verification) ---
disp('==== Per-slot Slice Prediction with GBR, Delay, Loss PROB (First 5 Slots) ====');
for slotIdx = 1:min(numSlots, 5) % Show only the first few slots for clarity
    for ueIdx = 1:numUEs
        predictedSliceIdx = simulationResults(slotIdx, ueIdx, 6); % Column 6: Slice Prediction Index
        
        % *** FIXED: Calculate GBR based on the predicted slice index (using 0.1 multiplier) ***
        gbr = gbrValues(predictedSliceIdx);
        
        delay = simulationResults(slotIdx, ueIdx, 3); % Column 3: Latency
        
        % *** MODIFIED: Read the floating-point probability from the new Column 8 ***
        % Assuming simulationResults was saved with 8 columns, where Col 8 = finalPLR
        plr_probability = simulationResults(slotIdx, ueIdx, 8); 
        
        % We also keep the binary outcome from Column 7 for context
        plr_binary = simulationResults(slotIdx, ueIdx, 7);
        
        disp(['Slot ', num2str(slotIdx), ', UE ', num2str(ueIdx), ...
              ': Slice = ', sliceNames{predictedSliceIdx}, ...
              ', GBR = ', num2str(gbr, '%.2f'), ...
              ', Delay = ', num2str(delay, '%.6f'), ... % Higher precision for delay
              ', Loss PROB = ', num2str(plr_probability, '%.12e'), ... % *** Displays exact scientific notation probability ***
              ', Loss (BIN) = ', num2str(plr_binary, '%.0f')]);
    end
end

%% --- 2. Calculate Average KPIs per Slice ---
avgGBR_perSlice = zeros(1, 3);
avgLatency = zeros(1, 3);
avgPLR = zeros(1, 3); 
sliceUsageCounts = zeros(1, 3);

for s = 1:3
    % Filter data for the current Slice Index (s)
    indices = simulationResults(:, :, 6) == s; 
    
    % 1. Average GBR (Use the pre-calculated fixed value for the slice)
    avgGBR_perSlice(s) = gbrValues(s);
    
    % 2. Average Latency (Correctly using Column 3)
    sliceDelay = simulationResults(:, :, 3);
    avgLatency(s) = mean(sliceDelay(indices), 'all');
    
    % 3. Average PLR (Correctly using Column 7 - the binary outcome)
    slicePLR = simulationResults(:, :, 7);
    avgPLR(s) = mean(slicePLR(indices), 'all');
    
    % 4. Usage Count
    sliceUsageCounts(s) = sum(indices, 'all');
end

%% --- 3. Visualization Plots ---

% A. GBR Performance per Slice
figure;
bar(avgGBR_perSlice, 'FaceColor', [0.3 0.7 0.9]);
set(gca, 'XTickLabel', sliceNames);
title('Average Guaranteed Bit Rate (GBR) per Slice');
ylabel('Average GBR (Mbps)');
grid on;

% B. Latency Performance per Slice
figure;
bar(avgLatency, 'FaceColor', [0.8 0.4 0.2]);
set(gca, 'XTickLabel', sliceNames);
title('Average Latency per Slice (URLLC Priority)');
ylabel('Average Latency (ms)');
grid on;

% C. Packet Loss Rate per Slice (using the binary result for the average)
figure;
bar(avgPLR * 100, 'FaceColor', [0.9 0.2 0.2]); % Plot in percentage
set(gca, 'XTickLabel', sliceNames);
title('Average Packet Loss Rate (PLR) per Slice');
ylabel('Average PLR (%)');
grid on;

% D. Slice Usage Distribution (Pie Chart)
figure;
pie(sliceUsageCounts, sliceNames);
title('DNN-Predicted Slice Usage Distribution');

% E. Allocation Heatmap (Which UE got which Slice over Time)
sliceMatrix = squeeze(simulationResults(:, :, 6)); % extract slice predictions (Column 6)
figure;
imagesc(sliceMatrix');
colormap(jet(3));
colorbar('Ticks', 1:3, 'TickLabels', {'eMBB', 'URLLC', 'mMTC'});
xlabel('Slot Index'); ylabel('UE Index');
title('Predicted 5G Allocation Heatmap (Time vs. UE)');
set(gca, 'YDir', 'normal'); % Flip Y-axis to standard matrix orientation